#!sh

perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 304_ST_ALL_Same_snps 304_ST_Same_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 304_SR_ALL_Same_snps 304_SR_Same_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 304_PV_ALL_Same_snps 304_PV_Same_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 307_ST_ALL_Same_snps 307_ST_Same_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 307_SR_ALL_Same_snps 307_SR_Same_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 307_PV_ALL_Same_snps 307_PV_Same_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 360_ST_ALL_Same_snps 360_ST_Same_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 360_SR_ALL_Same_snps 360_SR_Same_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 399_ST_ALL_Same_snps 399_ST_Same_masked

perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 304_ST_ALL_distinguishingSNPs 304_ST_Diff_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 304_SR_ALL_distinguishingSNPs 304_SR_Diff_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 304_PV_ALL_distinguishingSNPs 304_PV_Diff_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 307_ST_ALL_distinguishingSNPs 307_ST_Diff_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 307_SR_ALL_distinguishingSNPs 307_SR_Diff_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 307_PV_ALL_distinguishingSNPs 307_PV_Diff_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 360_ST_ALL_distinguishingSNPs 360_ST_Diff_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 360_SR_ALL_distinguishingSNPs 360_SR_Diff_masked
perl /home/juliecridland/scripts/same_snps_in_masked_regions.pl Lack_parsed_tableS3.txt 399_ST_ALL_distinguishingSNPs 399_ST_Diff_masked
